package com.edanurhamurcu.newsfeedapp.ui.fragments

import android.os.Build
import android.os.Bundle
import android.view.View
import android.webkit.WebViewClient
import androidx.annotation.RequiresApi
import androidx.fragment.app.Fragment
import androidx.navigation.fragment.navArgs
import com.edanurhamurcu.newsfeedapp.R
import com.edanurhamurcu.newsfeedapp.ui.NewsActivity
import com.edanurhamurcu.newsfeedapp.ui.NewsViewModel
import com.google.android.material.snackbar.Snackbar
import kotlinx.android.synthetic.main.fragment_article.*

class ArticleFragment : Fragment(R.layout.fragment_article){

    lateinit var viewModel: NewsViewModel
    private val args: ArticleFragmentArgs by navArgs() //ArticleFragmentArgs is generated by navigation component when we add the args

    @RequiresApi(Build.VERSION_CODES.M)
    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        viewModel= (activity as NewsActivity).viewModel

        //get the current article that was passed as arguments to this fragment
        val article = args.article
        webView.apply {
            webViewClient= WebViewClient()
            loadUrl(article.url.toString())
        }

        //save article
        fab.setOnClickListener{
            viewModel.saveArticle(article)
            Snackbar.make(view, " Article Saved Successfully! ", Snackbar.LENGTH_SHORT).show()
        }


    }
}